Hw2
solarps/andrii-yevstratiev pull request #2
Opened 2022-06-24 18:22 UTC by solarps

2022-07-11 21:44 UTC, romansokyrko requested changes

2022-07-11 21:44 UTC, romansokyrko commented on .idea/workspace.xml
>  <?xml version="1.0" encoding="UTF-8"?>
Please, ignore all files inside of .idea folder

2022-07-11 21:44 UTC, romansokyrko commented on src/main/java/com/epam/spring/homework2/beans/BeanC.java
> +@PropertySource("classpath:dev.properties")
Why is it needed?

2022-07-11 21:44 UTC, romansokyrko commented on src/main/java/com/epam/spring/homework2/beans/BeanD.java
> +@PropertySource("classpath:dev.properties")
Why is it needed?

2022-07-11 21:44 UTC, romansokyrko commented on src/main/java/com/epam/spring/homework2/postprocessors/BeanValidatorPostProcessor.java
> +    if (bean instanceof AbstractBean) {
Maybe it makes more sense to put this logic inside of postProcessAfterInitialization?

2022-07-11 21:44 UTC, romansokyrko commented on src/main/java/com/epam/spring/homework2/postprocessors/BeanValidatorPostProcessor.java
> +  public Object postProcessAfterInitialization(Object bean, String beanName) throws BeansException {
There is no need to override this method if no logic is added

2022-07-11 21:44 UTC, romansokyrko commented on src/main/java/com/epam/spring/homework2/postprocessors/BeanValidatorPostProcessor.java
> +  private void validate(AbstractBean abstractBean) {
JFYI: usually it is not expected from validator to set default values. More convenient behavior would be to throw an error if object is not in valid state.

Still, if you want to provide default values, pls try to avoid literals and magic numbers. It would be cleaner to have some constants e.g. DEFAULT_NAME and DEFAULT_VALUE.

2022-07-11 21:44 UTC, romansokyrko commented on src/main/java/com/epam/spring/homework2/Application.java
> +    Stream.of(context.getBeanDefinitionNames()).forEach(System.out::println);
Please, print all the bean definitions as well (item #12 in homework)

2022-07-14 08:16 UTC, solarps commented on src/main/java/com/epam/spring/homework2/postprocessors/BeanValidatorPostProcessor.java
> +    if (bean instanceof AbstractBean) {
Could you advise me to read something about proxies?
I thought that postProcessBeforeInitialization wraps up beans in a proxies and condition if (bean instanceof AbstractBean) in postProcessAfterInitialization will not work

2022-07-14 20:25 UTC, romansokyrko approved these changes
Approved, you can merge

2022-07-14 20:28 UTC, romansokyrko commented on src/main/java/com/epam/spring/homework2/postprocessors/BeanValidatorPostProcessor.java
> +    if (bean instanceof AbstractBean) {
In order for proxy to work - it should extend class that it is proxying. In that way instanceof operator is working on proxies as well.

2022-07-28 11:31 UTC, closed without merging